/**
 * Clase Vista: ConfiguracionReglasDescuento
 * * Propósito: Proporcionar una interfaz administrativa para gestionar las reglas
 * de fidelización (descuentos por puntos) aplicadas a las categorías del sistema SCTA.
 */
package Vista;

import Conexion.Conexión;
import Controlador.Ctrl_ReglaDescuento;
import Modelo.ReglaDescuento;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ConfiguracionReglasDescuento extends javax.swing.JInternalFrame {

    // Identificadores de estado para control de persistencia
    private int idCategoria = 0;

    /**
     * Constructor: Inicializa componentes, carga datos de BD y aplica estilos
     * visuales.
     */
    public ConfiguracionReglasDescuento() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Reglas de Descuento.");

        // Carga inicial de datos desde la base de datos
        this.cargarTablaReglas();

        // --- Configuración de Interfaz de Usuario (UI) ---
        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

        // Estilización de la tabla (Colores y Dimensiones)
        jTable_productos.setSelectionBackground(new Color(51, 153, 255));
        jTable_productos.setSelectionForeground(Color.WHITE);
        jTable_productos.setRowHeight(30);
        jTable_productos.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        jTable_productos.getTableHeader().setBackground(new Color(32, 136, 203));
        jTable_productos.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

        jTable_productos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int fila_visual = jTable_productos.getSelectedRow();
                if (fila_visual != -1) {
                    int fila_modelo = jTable_productos.convertRowIndexToModel(fila_visual);
                    String idStr = jTable_productos.getModel().getValueAt(fila_modelo, 0).toString();
                    idCategoria = Integer.parseInt(idStr);
                    EnviarDatosReglaSeleccionada(idCategoria);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_refrescar = new javax.swing.JButton();
        jButton_actualizar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_porcentajeDescuento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_puntosRequeridos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(46, 204, 113));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jButton_refrescar.setBackground(new java.awt.Color(46, 204, 113));
        jButton_refrescar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_refrescar.setText("Refrescar");
        jButton_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, -1));

        jButton_actualizar1.setBackground(new java.awt.Color(231, 76, 60));
        jButton_actualizar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar1.setText("Eliminar");
        jButton_actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 130, 370));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Porcentaje de Descuento:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 190, 20));

        txt_porcentajeDescuento.setText(" ");
        txt_porcentajeDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_porcentajeDescuentoActionPerformed(evt);
            }
        });
        txt_porcentajeDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_porcentajeDescuentoKeyTyped(evt);
            }
        });
        jPanel3.add(txt_porcentajeDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Puntos Requeridos:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        txt_puntosRequeridos.setText(" ");
        txt_puntosRequeridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puntosRequeridosActionPerformed(evt);
            }
        });
        txt_puntosRequeridos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_puntosRequeridosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_puntosRequeridosKeyTyped(evt);
            }
        });
        jPanel3.add(txt_puntosRequeridos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 870, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reglas de Descuento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 370));

        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento: Actualizar/Guardar Regla Lógica: Valida la selección de una
     * categoría, verifica que los campos no estén vacíos y envía el objeto
     * ReglaDescuento al controlador para su persistencia.
     */
    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
//         TODO add your handling code here:

        ReglaDescuento reglaDescuento = new ReglaDescuento();
        Ctrl_ReglaDescuento controlregla = new Ctrl_ReglaDescuento();

        if (idCategoria == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una regla de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txt_puntosRequeridos.getText().trim().isEmpty() || txt_porcentajeDescuento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea guardar los cambios para esta categoría?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    reglaDescuento.setPuntosRequeridos(Integer.parseInt(txt_puntosRequeridos.getText().trim()));
                    reglaDescuento.setPorcentajeDescuento(Double.parseDouble(txt_porcentajeDescuento.getText().trim()));

                    if (controlregla.actualizarReglas(reglaDescuento, idCategoria)) {
                        JOptionPane.showMessageDialog(this, "Regla Guardada/Actualizada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                        this.cargarTablaReglas();
                        this.limpiar();
                        idCategoria = 0;
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al procesar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Error: Ingrese valores numéricos válidos.", "Error de formato", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * Evento: Refrescar Tabla Fuerza la re-consulta de la base de datos para
     * mostrar cambios externos.
     */
    private void jButton_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarActionPerformed
        // TODO add your handling code here:

        this.cargarTablaReglas();

    }//GEN-LAST:event_jButton_refrescarActionPerformed

    private void txt_puntosRequeridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puntosRequeridosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puntosRequeridosActionPerformed

    private void txt_porcentajeDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_porcentajeDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_porcentajeDescuentoActionPerformed

    /**
     * Mejora de UX: Al presionar Enter en 'puntos', el cursor salta a
     * 'porcentaje'.
     */
    private void txt_puntosRequeridosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_puntosRequeridosKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            txt_porcentajeDescuento.requestFocus();
        }

    }//GEN-LAST:event_txt_puntosRequeridosKeyPressed

    /**
     * Validación de Entrada: Restringe el teclado solo a números para evitar
     * excepciones de formato.
     */
    private void txt_puntosRequeridosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_puntosRequeridosKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        // Solo permite números 
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume(); // Ignora la tecla
        }

    }//GEN-LAST:event_txt_puntosRequeridosKeyTyped

    /**
     * Validación de Entrada: Restringe el teclado solo a números para evitar
     * excepciones de formato.
     */
    private void txt_porcentajeDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_porcentajeDescuentoKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        // Solo permite números 
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume(); // Ignora la tecla
        }

    }//GEN-LAST:event_txt_porcentajeDescuentoKeyTyped

    private void jButton_actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar1ActionPerformed
        // TODO add your handling code here:
        Ctrl_ReglaDescuento regladescuento = new Ctrl_ReglaDescuento();

        if (idCategoria == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una regla de la tabla.");
        } else {
            // Añadiendo el cuadro de confirmación
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar esta regla?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                if (regladescuento.EliminarReglas(idCategoria)) {
                    JOptionPane.showMessageDialog(null, "¡Producto Eliminado correctamente!");

                    this.cargarTablaReglas();
                    idCategoria = 0;
                    this.limpiar();

                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar la regla.");
                }
            }
        }

    }//GEN-LAST:event_jButton_actualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_actualizar1;
    private javax.swing.JButton jButton_refrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JTextField txt_porcentajeDescuento;
    private javax.swing.JTextField txt_puntosRequeridos;
    // End of variables declaration//GEN-END:variables

    /**
     * Método: cargarTablaReglas Lógica: Realiza un LEFT JOIN entre 'categoria'
     * y 'regla_descuento'. Si una categoría no tiene regla, asigna valores "0"
     * y "0.0" por defecto.
     */
    private void cargarTablaReglas() {
        Connection cn = Conexión.conectar();

        // 1. Definimos el modelo de forma que no sea editable
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // 2. Agregamos las columnas ANTES de cargar los datos
        model.addColumn("ID");
        model.addColumn("Categoría");
        model.addColumn("Puntos Requeridos");
        model.addColumn("% Descuento");

        // 3. Consulta SQL corregida con LEFT JOIN para ver todas las categorías
        // Agregamos r.id_regla a la consulta
        String sql = "SELECT c.id_categoria, c.descripcion, r.puntos_requeridos, r.porcentaje_descuento, r.id_regla "
                + "FROM categoria c "
                + "LEFT JOIN regla_descuento r ON c.id_categoria = r.id_categoria";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object fila[] = new Object[4];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);

                // Manejo de nulos para categorías sin reglas aún
                Object puntos = rs.getObject(3);
                Object porcentaje = rs.getObject(4);
                fila[2] = (puntos != null) ? puntos : "0";
                fila[3] = (porcentaje != null) ? porcentaje : "0.0";

                model.addRow(fila);
            }

            // 4. IMPORTANTE: Solo actualizamos el modelo, no creamos la tabla de nuevo
            jTable_productos.setModel(model);

            // Configuraciones visuales
            jTable_productos.setRowHeight(30);
            jTable_productos.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla de reglas: " + e);
        }
    }

    private void limpiar() {
        txt_porcentajeDescuento.setText("");
        txt_puntosRequeridos.setText("");
    }

    private void EnviarDatosReglaSeleccionada(int idCategoria) {
        // CAMBIO: Buscamos por id_categoria en lugar de id_regla
        String sql = "SELECT puntos_requeridos, porcentaje_descuento, id_regla "
                + "FROM regla_descuento WHERE id_categoria = ?";

        try {
            Connection con = Conexión.conectar();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idCategoria); // Usamos el parámetro que recibe el método
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_puntosRequeridos.setText(rs.getString("puntos_requeridos"));
                txt_porcentajeDescuento.setText(rs.getString("porcentaje_descuento"));

            } else {
                // Si la categoría no tiene regla, limpiamos los campos y ponemos idRegla en 0
                this.limpiar();
                this.idCategoria = 0;
            }
            con.close();
        } catch (SQLException e) {
            System.err.println("Error al obtener datos de la regla por categoría: " + e);
        }
    }

}
