package Vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public static JDesktopPane jDesktopPane_menu;
    private Image fondoMenu;

    public FrmMenu() {
        initComponents();
        configurarVentana();
        cargarFondo();
    }

    private void configurarVentana() {
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas - SCTA");

        this.setLayout(new BorderLayout());
        jDesktopPane_menu = new JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (fondoMenu != null) {
                    Graphics2D g2d = (Graphics2D) g;
                    // Mejora la calidad del escalado de la imagen
//                    g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                    g2d.drawImage(fondoMenu, 0, 0, getWidth(), getHeight(), this);

                }
            }
        };
        // En configurarVentana()
        jDesktopPane_menu.putClientProperty("JDesktopPane.dragMode", "faster");
        this.add(jDesktopPane_menu, BorderLayout.CENTER);
    }

    private void cargarFondo() {
        try {
            java.net.URL imgUrl = getClass().getResource("/imagenes/fondo_menu2.png");
            if (imgUrl != null) {
                fondoMenu = new ImageIcon(imgUrl).getImage();
            }
        } catch (Exception e) {
            System.err.println("Error al cargar imagen de fondo: " + e.getMessage());
        }
    }

    /**
     * Método optimizado para evitar abrir ventanas duplicadas
     */
    private void abrirVentanaInterna(JInternalFrame ventana) {
        // Opcional: Lógica para verificar si ya hay una instancia abierta
        boolean estaAbierta = false;
        for (JInternalFrame f : jDesktopPane_menu.getAllFrames()) {
            if (f.getClass().equals(ventana.getClass())) {
                estaAbierta = true;
                f.toFront(); // La trae al frente si ya existe
                try {
                    f.setSelected(true);
                } catch (Exception e) {
                }
                break;
            }
        }

        if (!estaAbierta) {
            jDesktopPane_menu.add(ventana);
            ventana.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_gestionarUsuario = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_consultadeproductos = new javax.swing.JMenuItem();
        jMenuItem_registrodemercancias = new javax.swing.JMenuItem();
        jMenuItem_configuraciondeproductos = new javax.swing.JMenuItem();
        jMenuItem_ajustedeinventario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_nuevacategoria = new javax.swing.JMenuItem();
        jMenuItem_gestionarcategorias = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem_nuevaventa = new javax.swing.JMenuItem();
        jMenuItem_gestionarventas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_gestiondeprecios = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem_catalogodeproveedores = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_reportesclientes = new javax.swing.JMenuItem();
        jMenuItem_reportescategorias = new javax.swing.JMenuItem();
        jMenuItem_reportesproductos = new javax.swing.JMenuItem();
        jMenuItem_reportesventas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_nuevocliente = new javax.swing.JMenuItem();
        jMenuItem_gestionarclientes = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_cerrarsesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jMenu6.setText("Usuario");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_gestionarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jMenuItem_gestionarUsuario.setText("Cambiar Credenciales");
        jMenuItem_gestionarUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_gestionarUsuario);

        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/password.png"))); // NOI18N
        jMenuItem5.setText("Cambiar Pregunta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        jMenu1.setText("Inventarios");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_consultadeproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_consultadeproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        jMenuItem_consultadeproductos.setText("Consulta de Productos");
        jMenuItem_consultadeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_consultadeproductosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_consultadeproductos);

        jMenuItem_registrodemercancias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_registrodemercancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-producto.png"))); // NOI18N
        jMenuItem_registrodemercancias.setText("Registro de Productos");
        jMenuItem_registrodemercancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_registrodemercanciasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_registrodemercancias);

        jMenuItem_configuraciondeproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_configuraciondeproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jMenuItem_configuraciondeproductos.setText("Configuración de Productos");
        jMenuItem_configuraciondeproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_configuraciondeproductosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_configuraciondeproductos);

        jMenuItem_ajustedeinventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_ajustedeinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem_ajustedeinventario.setText("Entrada de Productos");
        jMenuItem_ajustedeinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ajustedeinventarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_ajustedeinventario);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem2.setText("Ajuste de Inventario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        jMenu7.setText("Categorías");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevacategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_nuevacategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem_nuevacategoria.setText("Nueva Categoría");
        jMenuItem_nuevacategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevacategoriaActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_nuevacategoria);

        jMenuItem_gestionarcategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarcategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        jMenuItem_gestionarcategorias.setText("Gestionar Categorías");
        jMenuItem_gestionarcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarcategoriasActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_gestionarcategorias);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial1.png"))); // NOI18N
        jMenuItem4.setText("Reglas de Descuento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem4);

        jMenuBar1.add(jMenu7);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        jMenu9.setText("Punto de Venta");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_nuevaventa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_nuevaventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jMenuItem_nuevaventa.setText("Nueva Venta");
        jMenu9.add(jMenuItem_nuevaventa);

        jMenuItem_gestionarventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        jMenuItem_gestionarventas.setText("Gestionar Ventas");
        jMenu9.add(jMenuItem_gestionarventas);

        jMenuBar1.add(jMenu9);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenu2.setText("Precios");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_gestiondeprecios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestiondeprecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_gestiondeprecios.setText("Gestión de Precios");
        jMenuItem_gestiondeprecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestiondepreciosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_gestiondeprecios);

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-cliente.png"))); // NOI18N
        jMenuItem6.setText("Nuevo Proveedor");
        jMenu2.add(jMenuItem6);

        jMenuItem_catalogodeproveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_catalogodeproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_catalogodeproveedores.setText("Catálogo de Proveedores");
        jMenu2.add(jMenuItem_catalogodeproveedores);

        jMenuBar1.add(jMenu2);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenu8.setText("Reportes");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_reportesclientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportesclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportesclientes.setText("Reportes de Clientes");
        jMenu8.add(jMenuItem_reportesclientes);

        jMenuItem_reportescategorias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportescategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportescategorias.setText("Reportes de Categorias");
        jMenu8.add(jMenuItem_reportescategorias);

        jMenuItem_reportesproductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportesproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportesproductos.setText("Reportes de Productos");
        jMenu8.add(jMenuItem_reportesproductos);

        jMenuItem_reportesventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_reportesventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenuItem_reportesventas.setText("Reportes de Ventas");
        jMenu8.add(jMenuItem_reportesventas);

        jMenuBar1.add(jMenu8);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        jMenu4.setText("Fidelización");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevocliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_nuevocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-cliente.png"))); // NOI18N
        jMenuItem_nuevocliente.setText("Nuevo Cliente");
        jMenuItem_nuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevoclienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_nuevocliente);

        jMenuItem_gestionarclientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_gestionarclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        jMenuItem_gestionarclientes.setText("Gestionar Clientes");
        jMenuItem_gestionarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionarclientesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gestionarclientes);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial1.png"))); // NOI18N
        jMenuItem3.setText("Consulta de Puntos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(175, 50));

        jMenuItem_cerrarsesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuItem_cerrarsesion.setText("Cerrar Sesión");
        jMenuItem_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cerrarsesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_cerrarsesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_nuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevoclienteActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem_nuevoclienteActionPerformed

    private void jMenuItem_nuevacategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevacategoriaActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterCategoria());

    }//GEN-LAST:event_jMenuItem_nuevacategoriaActionPerformed

    private void jMenuItem_gestionarcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarcategoriasActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterGestionarCategorias());

    }//GEN-LAST:event_jMenuItem_gestionarcategoriasActionPerformed

    private void jMenuItem_registrodemercanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_registrodemercanciasActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterProducto());

    }//GEN-LAST:event_jMenuItem_registrodemercanciasActionPerformed

    private void jMenuItem_consultadeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_consultadeproductosActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterConsultaProductos());

    }//GEN-LAST:event_jMenuItem_consultadeproductosActionPerformed

    private void jMenuItem_configuraciondeproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_configuraciondeproductosActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterConfiguracionProductos());

    }//GEN-LAST:event_jMenuItem_configuraciondeproductosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterAjusteInventario());

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem_ajustedeinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ajustedeinventarioActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterEntradaProductos());

    }//GEN-LAST:event_jMenuItem_ajustedeinventarioActionPerformed

    private void jMenuItem_gestionarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarclientesActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem_gestionarclientesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new ConfiguracionReglasDescuento());

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem_gestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionarUsuarioActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterGestionUsuario());

    }//GEN-LAST:event_jMenuItem_gestionarUsuarioActionPerformed

    private void jMenuItem_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cerrarsesionActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new SCTALogin().setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Sesión Cerrada", "Sesión Cerrada", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem_cerrarsesionActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        abrirVentanaInterna(new InterGestionPregunta());

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem_gestiondepreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestiondepreciosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem_gestiondepreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_ajustedeinventario;
    private javax.swing.JMenuItem jMenuItem_catalogodeproveedores;
    private javax.swing.JMenuItem jMenuItem_cerrarsesion;
    private javax.swing.JMenuItem jMenuItem_configuraciondeproductos;
    private javax.swing.JMenuItem jMenuItem_consultadeproductos;
    private javax.swing.JMenuItem jMenuItem_gestionarUsuario;
    private javax.swing.JMenuItem jMenuItem_gestionarcategorias;
    private javax.swing.JMenuItem jMenuItem_gestionarclientes;
    private javax.swing.JMenuItem jMenuItem_gestionarventas;
    private javax.swing.JMenuItem jMenuItem_gestiondeprecios;
    private javax.swing.JMenuItem jMenuItem_nuevacategoria;
    private javax.swing.JMenuItem jMenuItem_nuevaventa;
    private javax.swing.JMenuItem jMenuItem_nuevocliente;
    private javax.swing.JMenuItem jMenuItem_registrodemercancias;
    private javax.swing.JMenuItem jMenuItem_reportescategorias;
    private javax.swing.JMenuItem jMenuItem_reportesclientes;
    private javax.swing.JMenuItem jMenuItem_reportesproductos;
    private javax.swing.JMenuItem jMenuItem_reportesventas;
    // End of variables declaration//GEN-END:variables
}
