package Vista;

import Conexion.Conexión;
import Controlador.Ctrl_Categoria;
import Modelo.categoria;
import java.awt.Color;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana interna para la administración de categorías existentes. Proporciona
 * una interfaz para listar, actualizar y eliminar las clasificaciones de
 * productos en el sistema.
 *
 * * @author lsuar
 */
public class InterGestionarCategorias extends javax.swing.JInternalFrame {

    /**
     * Almacena el ID de la categoría seleccionada en la tabla.
     */
    private int idCategoria = 0;

    /**
     * Constructor de la clase. Inicializa componentes, configura el diseño
     * visual de la tabla y establece el listener para la selección de filas.
     */
    public InterGestionarCategorias() {
        initComponents();
        this.setSize(new Dimension(600, 400));
        this.setTitle("Gestionar Categorias.");

        // Carga inicial de datos desde MySQL
        this.cargarTablaCategoria();

        // Configuración estética de la tabla
        jTable_categoria.setSelectionBackground(new Color(51, 153, 255));
        jTable_categoria.setSelectionForeground(Color.WHITE);
        jTable_categoria.setRowHeight(30);
        jTable_categoria.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        jTable_categoria.getTableHeader().setBackground(new Color(32, 136, 203));

        // Listener para detectar clics en la tabla y cargar datos en el formulario lateral
        jTable_categoria.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int fila_visual = jTable_categoria.getSelectedRow();
                if (fila_visual != -1) {
                    int fila_modelo = jTable_categoria.convertRowIndexToModel(fila_visual);
                    String idStr = jTable_categoria.getModel().getValueAt(fila_modelo, 0).toString();
                    idCategoria = Integer.parseInt(idStr);
                    EnviarDatosCategoriaSeleccionada(idCategoria);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_categoria = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jButton_refrescar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestionar Categorias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_categoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jButton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 200, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Descripción:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_descripcion.setText(" ");
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 200, 70));

        jButton_refrescar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_refrescar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_refrescar.setText("Refrescar");
        jButton_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 180, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 200, 40));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Procesa la actualización de la descripción de una categoría. Requiere que
     * se haya seleccionado una categoría previamente.
     */
    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
        
        if (idCategoria == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una categoria de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!txt_descripcion.getText().isEmpty()) {

            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea actualizar la categoría seleccionada?", "Confirmar Actualización", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                categoria categoria = new categoria();
                Ctrl_Categoria controlcategoria = new Ctrl_Categoria();
                categoria.setDescripcion(txt_descripcion.getText().trim());

                if (controlcategoria.actualizar(categoria, idCategoria)) {
                    JOptionPane.showMessageDialog(null, "Categoria actualizada.");
                    txt_descripcion.setText("");
                    this.cargarTablaCategoria();
                    idCategoria = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar.");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una categoria.");
        }

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * Ejecuta la eliminación física de la categoría en la base de datos.
     */
    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        if (!txt_descripcion.getText().isEmpty()) {

            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar esta categoría?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                Ctrl_Categoria controlcategoria = new Ctrl_Categoria();
                if (controlcategoria.Eliminar(idCategoria)) {
                    JOptionPane.showMessageDialog(null, "Categoria eliminada.");
                    txt_descripcion.setText("");
                    this.cargarTablaCategoria();
                    idCategoria = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar.");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una categoria.");
        }

    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarActionPerformed
        // TODO add your handling code here:

        this.cargarTablaCategoria();

    }//GEN-LAST:event_jButton_refrescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_refrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_categoria;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables

    /**
     * Consulta la base de datos y llena el DefaultTableModel con las
     * categorías. Configura la tabla para que las celdas no sean editables
     * directamente.
     */
    public void cargarTablaCategoria() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en celdas
            }
        };

        model.addColumn("ID");
        model.addColumn("Descripción");

        try {
            Connection con = Conexión.conectar();
            String sql = "select id_categoria, descripcion from categoria";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object fila[] = new Object[2];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                model.addRow(fila);
            }
            con.close();
            jTable_categoria.setModel(model);
            jTable_categoria.getColumnModel().getColumn(0).setPreferredWidth(10);
        } catch (SQLException e) {
            System.out.println("Error al cargar la tabla: " + e);
        }
    }

    /**
     * Al seleccionar una fila, este método recupera los detalles completos de
     * la categoría desde MySQL y los coloca en el campo de texto.
     */
    private void EnviarDatosCategoriaSeleccionada(int idCategoria) {
        try {
            Connection con = Conexión.conectar();
            PreparedStatement pst = con.prepareStatement("select * from categoria where id_categoria = ?");
            pst.setInt(1, idCategoria);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_descripcion.setText(rs.getString("descripcion"));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar categoría.");
        }
    }

}
