/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexión;
import Controlador.Ctrl_Producto;
import Modelo.Producto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * CLASE: InterAjusteInventario FUNCIÓN: Permitir ajustes manuales de stock y
 * definir niveles de alerta (Stock Mínimo). CARACTERÍSTICAS: Uso de
 * TableRowSorter para filtrado en tiempo real y JSpinners para control
 * numérico.
 */
public class InterAjusteInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterAjusteInventario
     */
    private int idProducto = 0;
    private DefaultTableModel modeloInventario;
    private TableRowSorter<DefaultTableModel> sorter; // Permite realizar filtros de búsqueda

    public InterAjusteInventario() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Configuración de Productos.");
        this.configurarTabla();
        this.organizarPorCategorias();
        this.cargarCategorias();

        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

        jTable_productos.setSelectionBackground(new Color(51, 153, 255)); // Azul moderno al seleccionar
        jTable_productos.setSelectionForeground(Color.WHITE);

        jTable_productos.setRowHeight(30);

        jTable_productos.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        jTable_productos.getTableHeader().setBackground(new Color(32, 136, 203)); // Azul
        jTable_productos.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));
        jTable_productos.getColumnModel().getColumn(0).setPreferredWidth(10);

        // --- MANEJO DE SELECCIÓN EN TABLA ---
        jTable_productos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int fila_visual = jTable_productos.getSelectedRow();
                if (fila_visual != -1) {
                    int fila_modelo = jTable_productos.convertRowIndexToModel(fila_visual);
                    String idStr = jTable_productos.getModel().getValueAt(fila_modelo, 0).toString();
                    idProducto = Integer.parseInt(idStr);
                    EnviarDatosProductoSeleccionado(idProducto);
                }
            }
        });

    }

    /**
     * CONFIGURACIÓN DE TABLA Y RENDERIZADO Aquí se integra el RenderizadorStock
     * para que los productos con bajo stock se resalten visualmente (ej. en
     * rojo o amarillo).
     */
    private void configurarTabla() {
        modeloInventario = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloInventario.addColumn("ID");
        modeloInventario.addColumn("Nombre");
        modeloInventario.addColumn("Categoria");
        modeloInventario.addColumn("Proveedor");
        modeloInventario.addColumn("Stock Actual");
        modeloInventario.addColumn("Stock Minimo");
        jTable_productos.setModel(modeloInventario);

        // Renderizador único
        RenderizadorStock render = new RenderizadorStock();
        for (int i = 0; i < jTable_productos.getColumnCount(); i++) {
            jTable_productos.getColumnModel().getColumn(i).setCellRenderer(render);
        }

        jTable_productos.setModel(modeloInventario);
        sorter = new TableRowSorter<>(modeloInventario);
        jTable_productos.setRowSorter(sorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jComboBox_categorias = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_stockminimo = new javax.swing.JSpinner();
        jSpinner_stockactual = new javax.swing.JSpinner();
        jButton_refrescar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar Producto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jComboBox_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Item 2", "Item 3", "Item 4" }));
        jComboBox_categorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_categoriasItemStateChanged(evt);
            }
        });
        jComboBox_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 870, 370));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Stock Minimo:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Stock Actual:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        jSpinner_stockminimo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_stockminimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_stockminimoKeyTyped(evt);
            }
        });
        jPanel3.add(jSpinner_stockminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 8, 100, -1));

        jSpinner_stockactual.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        jSpinner_stockactual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner_stockactualKeyTyped(evt);
            }
        });
        jPanel3.add(jSpinner_stockactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 8, 100, -1));

        jButton_refrescar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_refrescar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_refrescar.setText("Refrescar");
        jButton_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 8, 110, -1));

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 8, 110, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 870, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt_buscar.setText(" ");
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 450, -1));

        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_categoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_categoriasItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            organizarPorCategorias();
            txt_buscar.setText("");
        }
    }//GEN-LAST:event_jComboBox_categoriasItemStateChanged

    private void jComboBox_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriasActionPerformed

    /**
     * ACCIÓN: Actualizar (Botón Verde) Envía los nuevos valores del JSpinner al
     * controlador para impactar la DB.
     */
    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:

        // 1. Validar que se haya seleccionado un producto
        if (idProducto == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla primero.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Mostrar pestaña de confirmación
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea actualizar el stock de este producto?",
                "Confirmar Actualización",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        // 3. Si el administrador selecciona "SÍ", se procede con la actualización
        if (respuesta == JOptionPane.YES_OPTION) {
            Producto producto = new Producto();
            Ctrl_Producto controlProducto = new Ctrl_Producto();

            try {
                producto.setStock_actual((int) jSpinner_stockactual.getValue());
                producto.setStock_minimo((int) jSpinner_stockminimo.getValue());

                if (controlProducto.actualizarAjusteInventario(producto, idProducto)) {
                    JOptionPane.showMessageDialog(this, "Producto Actualizado correctamente.", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    this.organizarPorCategorias();

                    // Limpiar selección para evitar actualizaciones duplicadas accidentales
                    idProducto = 0;
                    jSpinner_stockactual.setValue(0);
                    jSpinner_stockminimo.setValue(0);

                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error de formato: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        // Si selecciona "NO", el método termina y no pasa nada.


    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarActionPerformed
        // TODO add your handling code here:

        this.organizarPorCategorias();
    }//GEN-LAST:event_jButton_refrescarActionPerformed

    private void jSpinner_stockminimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_stockminimoKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        // Solo permite números 
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume(); // Ignora la tecla
        }

    }//GEN-LAST:event_jSpinner_stockminimoKeyTyped

    private void jSpinner_stockactualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner_stockactualKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        // Solo permite números 
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume(); // Ignora la tecla
        }

    }//GEN-LAST:event_jSpinner_stockactualKeyTyped

    /**
     * FILTRADO POR TEXTO (Buscador) Se ejecuta en el evento keyReleased: cada
     * vez que el usuario suelta una tecla.
     */
    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // TODO add your handling code here:

        String texto = txt_buscar.getText().trim();

        if (texto.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            // Filtra sin importar mayúsculas/minúsculas (?i)
            // El índice 1 corresponde a la columna "Nombre"
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
        }

    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        // TODO add your handling code here:

        // 1. Obtenemos el carácter presionado
        char car = evt.getKeyChar();

        // 2. Validamos si NO es letra, NO es dígito, NO es espacio, NO es punto y NO es coma
        if (!Character.isLetter(car) && !Character.isDigit(car) && car != ' ' && car != '.' && car != ',') {

            // 3. Si no cumple con ninguna de las anteriores, se "consume" el evento
            evt.consume();
        }

    }//GEN-LAST:event_txt_buscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_refrescar;
    private javax.swing.JComboBox<String> jComboBox_categorias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_stockactual;
    private javax.swing.JSpinner jSpinner_stockminimo;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void organizarPorCategorias() {
        // Limpiar filas actuales sin borrar columnas
        modeloInventario.setRowCount(0);

        String seleccion = jComboBox_categorias.getSelectedItem().toString();
        String sql = "SELECT p.id_producto, p.nombre, c.descripcion, prov.nombre, p.stock_actual, p.stock_minimo "
                + "FROM producto p "
                + "INNER JOIN categoria c ON p.id_categoria = c.id_categoria "
                + "INNER JOIN proveedor prov ON p.id_proveedor = prov.id_proveedor ";

        if (!seleccion.equals("Todos")) {
            sql += "WHERE c.descripcion = ?";
        }

        try (Connection cn = Conexión.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            if (!seleccion.equals("Todos")) {
                pst.setString(1, seleccion);
            }

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                Object fila[] = {rs.getInt(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getInt(5), rs.getInt(6)};
                modeloInventario.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e);
        }
    }

    /**
     * CARGA DE DATOS AL SELECCIONAR Consulta el stock actual y mínimo
     * directamente de la DB para asegurar datos frescos.
     */
    private void EnviarDatosProductoSeleccionado(int idProducto) {

        String sql = "select stock_actual, stock_minimo from producto where id_producto = ?";

        try {
            Connection con = Conexión.conectar();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idProducto);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                jSpinner_stockactual.setValue(rs.getInt("stock_actual"));
                jSpinner_stockminimo.setValue(rs.getInt("stock_minimo"));

            }
            con.close();
        } catch (SQLException e) {
            System.err.println("Error al obtener datos del producto: " + e);
        }
    }

    //Metodo que carga las categorias en el JComboBox
    private void cargarCategorias() {
        Connection cn = Conexión.conectar();
        String sql = "select * from categoria";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            jComboBox_categorias.removeAllItems();
            jComboBox_categorias.addItem("Todos");

            while (rs.next()) {

                jComboBox_categorias.addItem(rs.getString("descripcion"));
            }

            cn.close();

        } catch (SQLException e) {
        }

    }

}
