package Vista;

// Importación de librerías para manejo de BD, gráficos y componentes de Swing
import Conexion.Conexión;
import java.awt.Color;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lsuar
 */
public class InterConsultaProductos extends javax.swing.JInternalFrame {

    // Objetos para controlar los datos de la tabla y el filtrado en tiempo real
    private DefaultTableModel model;
    private TableRowSorter<DefaultTableModel> sorter;
    private RenderizadorStock render = new RenderizadorStock();

    public InterConsultaProductos() {
        initComponents(); // Inicializa los componentes creados por el diseñador de NetBeans
        this.setSize(new Dimension(1200, 676)); // Tamaño fijo para la ventana interna
        this.setTitle("Consulta Productos");

        // Métodos de configuración inicial
        this.configurarTabla();
        this.cargarCategorias();

        // --- Configuración del Fondo (Wallpaper) ---
        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo5.jpg");
        // Escalado de imagen para que coincida con el tamaño de la ventana
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(1200, 676, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

        // --- Personalización Visual de la Tabla ---
        jTable_producto.setSelectionBackground(new Color(51, 153, 255)); // Azul al seleccionar fila
        jTable_producto.setSelectionForeground(Color.WHITE);
        jTable_producto.setRowHeight(30); // Filas más altas para mejor legibilidad

        // Estilo del encabezado (Header)
        jTable_producto.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        jTable_producto.getTableHeader().setBackground(new Color(32, 136, 203));
        jTable_producto.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

        // Ajuste manual de anchos para columnas con datos pequeños
        jTable_producto.getColumnModel().getColumn(0).setPreferredWidth(20);  // ID
        jTable_producto.getColumnModel().getColumn(9).setPreferredWidth(20);  // IVA %
    }

    /**
     * Configura el modelo de la tabla para que no sea editable por el usuario
     */
    private void configurarTabla() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea la edición directa en las celdas
            }
        };

        // Definición de las columnas que requiere el SCTA
        String[] cabecera = {"ID", "Nombre", "Descripción", "Precio Uni", "Precio Provee",
            "Categoria", "Proveedor", "Stock Actual", "Stock Minimo", "IVA %", "Puntos", "Fecha"};
        model.setColumnIdentifiers(cabecera);
        jTable_producto.setModel(model);

        // Habilita el ordenamiento (clic en cabecera) y búsqueda
        sorter = new TableRowSorter<>(model);
        jTable_producto.setRowSorter(sorter);

        // Aplica el renderizador personalizado (ej. colores para stock bajo) a todas las columnas
        for (int i = 0; i < jTable_producto.getColumnCount(); i++) {
            jTable_producto.getColumnModel().getColumn(i).setCellRenderer(render);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_producto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_categorias = new javax.swing.JComboBox<>();
        txt_buscar_consulta = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_producto.setAutoCreateRowSorter(true);
        jTable_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_producto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1150, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1170, 590));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1066, 10, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jComboBox_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Item 2", "Item 3", "Item 4" }));
        jComboBox_categorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_categoriasItemStateChanged(evt);
            }
        });
        jComboBox_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, -1));

        txt_buscar_consulta.setText(" ");
        txt_buscar_consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscar_consultaKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 360, -1));

        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento al cambiar la categoría en el ComboBox
     */
    private void jComboBox_categoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_categoriasItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            txt_buscar_consulta.setText("");
            if (sorter != null) {
                sorter.setRowFilter(null);
            }
            organizarPorCategorias();
        }

    }//GEN-LAST:event_jComboBox_categoriasItemStateChanged

    /**
     * Botón para refrescar y mostrar todos los productos de nuevo
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jComboBox_categorias.setSelectedIndex(0);
        this.organizarPorCategorias();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriasActionPerformed

    /**
     * Filtrado dinámico mediante el campo de texto (Buscador)
     */
    private void txt_buscar_consultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_consultaKeyReleased
        // TODO add your handling code here:

        String busqueda = txt_buscar_consulta.getText().trim();
        // Filtra por la columna "Nombre" (índice 1)
        // (?i) es para que no distinga entre mayúsculas y minúsculas
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + busqueda, 1));


    }//GEN-LAST:event_txt_buscar_consultaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_categorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_producto;
    private javax.swing.JTextField txt_buscar_consulta;
    // End of variables declaration//GEN-END:variables

    /**
     * Lógica de consulta a Base de Datos con filtros dinámicos
     */
    private void organizarPorCategorias() {
        model.setRowCount(0); // Limpia la tabla para no duplicar datos nuevos

        Object selectedItem = jComboBox_categorias.getSelectedItem();
        if (selectedItem == null) {
            return;
        }
        String seleccion = selectedItem.toString();

        // SQL con INNER JOIN para traer nombres en vez de solo IDs de FK
        String sql = "SELECT p.id_producto, p.nombre, p.descripcion, p.precio_unitario, p.precio_proveedor, "
                + "c.descripcion AS categoria, prov.nombre AS proveedor, "
                + "p.stock_actual, p.stock_minimo, p.iva, p.puntos_otorgados, p.fecha_de_agregacion "
                + "FROM producto p "
                + "INNER JOIN categoria c ON p.id_categoria = c.id_categoria "
                + "INNER JOIN proveedor prov ON p.id_proveedor = prov.id_proveedor "
                + (seleccion.equals("Todos") ? "" : "WHERE c.descripcion = ?");

        // Uso de Try-with-resources para asegurar el cierre de conexión
        try (Connection cn = Conexión.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            if (!seleccion.equals("Todos")) {
                pst.setString(1, seleccion); // Asigna la categoría al parámetro '?'
            }

            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    // Crea un array de objetos con las 12 columnas obtenidas
                    Object[] fila = new Object[12];
                    for (int i = 0; i < 12; i++) {
                        fila[i] = rs.getObject(i + 1);
                    }
                    model.addRow(fila); // Agrega la fila al modelo de la tabla
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al filtrar: " + e);
        }
    }

    /**
     * Carga inicial del ComboBox desde la tabla de categorías
     */
    private void cargarCategorias() {
        String sql = "SELECT descripcion FROM categoria";
        try (Connection cn = Conexión.conectar(); PreparedStatement pst = cn.prepareStatement(sql); ResultSet rs = pst.executeQuery()) {

            jComboBox_categorias.removeAllItems();
            jComboBox_categorias.addItem("Todos");

            while (rs.next()) {
                jComboBox_categorias.addItem(rs.getString("descripcion"));
            }

        } catch (SQLException e) {
            System.err.println("Error al cargar categorías: " + e);
        }
    }

}
