package Vista;

import Controlador.Ctrl_Usuario;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 * Ventana interna para la gestión de credenciales de acceso. Permite al
 * administrador actualizar su nombre de usuario y contraseña de manera segura
 * dentro del sistema SCTA.
 *
 * * @author lsuar
 */
public class InterGestionUsuario extends javax.swing.JInternalFrame {

    /**
     * ID del usuario a modificar. Por defecto es 1 (Administrador principal).
     */
    private int idUsuario = 1;

    /**
     * Constructor de la interfaz. Inicializa los componentes visuales y define
     * el título y dimensiones de la ventana interna.
     */
    public InterGestionUsuario() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Cambio de Credenciales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_guardar = new javax.swing.JButton();
        jCheckBox_verPassword = new javax.swing.JCheckBox();
        txt_password = new javax.swing.JPasswordField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cambio de Credenciales");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        jTextField_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/password.png"))); // NOI18N
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_guardar.setText("Actualizar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 240, -1));

        jCheckBox_verPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox_verPassword.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_verPassword.setText("Mostrar Contraseña");
        jCheckBox_verPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_verPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_verPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 240, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de acción para el botón actualizar. Dispara el proceso de
     * validación y persistencia de datos.
     */
    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:

        this.actualizar();

    }//GEN-LAST:event_jButton_guardarActionPerformed

    /**
     * Gestiona el flujo de foco mediante la tecla Enter. Al presionar Enter en
     * el campo de usuario, el cursor pasa al campo de contraseña.
     */
    private void jTextField_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usuarioKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            txt_password.requestFocus();
        }

    }//GEN-LAST:event_jTextField_usuarioKeyPressed

    /**
     * Controla la visibilidad del texto en el JPasswordField. Alterna entre el
     * carácter de eco estándar (•) y texto plano.
     */
    private void jCheckBox_verPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_verPasswordActionPerformed
        // TODO add your handling code here:

        if (jCheckBox_verPassword.isSelected()) {
            // Mostrar contraseña
            txt_password.setEchoChar((char) 0);
        } else {
            // Ocultar con el punto estándar
            txt_password.setEchoChar('•');
        }

    }//GEN-LAST:event_jCheckBox_verPasswordActionPerformed

    /**
     * Permite ejecutar la actualización directamente al presionar Enter desde
     * el campo de contraseña.
     */
    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.actualizar();
        }

    }//GEN-LAST:event_txt_passwordKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JCheckBox jCheckBox_verPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField jTextField_usuario;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables

    /**
     * Restablece los campos de texto a su estado inicial.
     */
    private void limpiar() {
        jTextField_usuario.setText("");
        txt_password.setText("");
    }

    /**
     * Proceso principal de actualización de credenciales. 
     * 1. Valida que los campos no estén vacíos. 
     * 2. Solicita confirmación al usuario. 
     * 3. Envía los datos al Controlador para impactar la base de datos MySQL.
     */
    private void actualizar() {

        Usuario usuario = new Usuario();
        Ctrl_Usuario controlUsuario = new Ctrl_Usuario();
        String password = new String(txt_password.getPassword());

        if (jTextField_usuario.getText().trim().isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea guardar los cambios?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {

                usuario.setNombre(jTextField_usuario.getText().trim());
                usuario.setPassword(password);

                if (controlUsuario.actualizarUsuario(usuario, idUsuario)) {
                    JOptionPane.showMessageDialog(this, "Datos Actualizados con Éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    this.limpiar();           // Limpia campos y resetea ID

                } else {
                    JOptionPane.showMessageDialog(this, "Error al procesar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }

    }

}
