package Vista;

import Controlador.Ctrl_Usuario;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 * Diálogo modal para la recuperación de acceso mediante pregunta de seguridad.
 * Esta ventana se despliega cuando el usuario olvida su contraseña principal,
 * permitiendo el ingreso al sistema tras validar una respuesta preconfigurada.
 *
 * * @author lsuar
 */
public class InterPreguntaAcceso extends javax.swing.JDialog {

    /**
     * Constructor del diálogo.
     *
     * @param parent El Frame padre (usualmente el FrmLogin) que invoca este
     * diálogo.
     * @param modal Define si el diálogo bloquea o no el resto de las ventanas.
     */
    public InterPreguntaAcceso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Configuración de interfaz
        this.setLocationRelativeTo(parent); // Centrado sobre el Login
        this.setSize(new Dimension(400, 300));
        this.setTitle("Pregunta de Acceso");
        this.setResizable(false);

        // Carga la pregunta desde la base de datos al iniciar
        this.mostrarPregunta();

        // Establece el foco inicial en el campo de texto
        jTextField1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton_guardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JPasswordField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pregunta de Acceso");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 250, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Pregunta");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_guardar.setText("Ingresar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        jButton_guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_guardarKeyPressed(evt);
            }
        });
        jPanel2.add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Respuesta:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setText("Mostrar Respuesta");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 52, 260, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 170));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de acción del botón "Ingresar".
     */
    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:

        this.loginPorPregunta();

    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_guardarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_guardarKeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:

        if (jCheckBox1.isSelected()) {
            // Mostrar contraseña
            jTextField1.setEchoChar((char) 0);
        } else {
            // Ocultar con el punto estándar
            jTextField1.setEchoChar('•');
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterPreguntaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterPreguntaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterPreguntaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterPreguntaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterPreguntaAcceso dialog = new InterPreguntaAcceso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * Lógica de validación de acceso. Consulta al controlador si la respuesta
     * ingresada coincide con la del admin (ID 1). Si es correcta, abre el Menú
     * Principal y cierra la pantalla de Login.
     */
    private void loginPorPregunta() {
        // Validamos que el campo de respuesta no esté vacío
        if (!jTextField1.getText().isEmpty()) {

            Ctrl_Usuario controlusuario = new Ctrl_Usuario();
            Usuario usuario = new Usuario();

            // Pasamos la respuesta al objeto (usamos trim para evitar espacios)
            usuario.setRespuestapregunta(jTextField1.getText().trim());

            // Llamamos al método del controlador
            if (controlusuario.loginPorPreguntaUnico(usuario)) {

                FrmMenu menu = new FrmMenu();
                menu.setVisible(true);

                // Cerramos el JDialog y el JFrame padre (Login)
                this.dispose();
                java.awt.Window padre = javax.swing.SwingUtilities.getWindowAncestor(this);
                if (padre != null) {
                    padre.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Respuesta Incorrecta.", "Error.", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese su respuesta de seguridad.", "Error.", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarPregunta() {
        Ctrl_Usuario control = new Ctrl_Usuario();
        String pregunta = control.obtenerPreguntaSeguridad();

        if (pregunta != null && !pregunta.isEmpty()) {
            jLabel6.setText(pregunta);
        } else {
            jLabel6.setText("Pregunta no configurada.");
        }
    }

}
