package Vista;

import Controlador.Ctrl_Usuario;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 * Ventana interna para la gestión del mecanismo de recuperación de cuenta.
 * Permite al administrador seleccionar una pregunta de seguridad y establecer
 * una respuesta privada que será almacenada en la base de datos.
 *
 * * @author lsuar
 */
public class InterGestionPregunta extends javax.swing.JInternalFrame {

    /**
     * Identificador único del administrador en el sistema.
     */
    private int idUsuario = 1;

    /**
     * Constructor de la clase. Configura el tamaño, título y restricciones de
     * la ventana interna, asegurando que el diseño permanezca fijo para evitar
     * desajustes visuales.
     */
    public InterGestionPregunta() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Cambiar Pregunta y Respuesta de Seguridad");

        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_respuesta = new javax.swing.JPasswordField();
        jCheckBox_verPassword = new javax.swing.JCheckBox();
        jButton_guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_pregunta = new javax.swing.JComboBox<>();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("de Seguridad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Pregunta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Respuesta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 140, 120, -1));

        txt_respuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_respuestaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 270, -1));

        jCheckBox_verPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox_verPassword.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_verPassword.setText("Mostrar Respuesta");
        jCheckBox_verPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_verPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_verPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_guardar.setText("Actualizar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cambio de Pregunta Y Respuesta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, 30));

        jComboBox_pregunta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox_pregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Nombre de tu primera mascota?", "¿Segundo nombre de tu madre?", "¿Ciudad donde naciste?", "¿Tu color favorito?", "¿Tu deporte favorito?", "¿Tu superhéroe favorito?" }));
        jComboBox_pregunta.setMinimumSize(new java.awt.Dimension(64, 22));
        jComboBox_pregunta.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(jComboBox_pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 270, 30));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Listener para el campo de respuesta. Permite procesar la actualización al
     * presionar la tecla Enter.
     */
    private void txt_respuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_respuestaKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.actualizar();
        }
    }//GEN-LAST:event_txt_respuestaKeyPressed

    /**
     * Controla la visibilidad de la respuesta. Utiliza setEchoChar para ocultar
     * la respuesta con puntos o mostrarla en texto plano según el estado del
     * checkbox.
     */
    private void jCheckBox_verPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_verPasswordActionPerformed
        // TODO add your handling code here:

        if (jCheckBox_verPassword.isSelected()) {
            // Mostrar contraseña
            txt_respuesta.setEchoChar((char) 0);
        } else {
            // Ocultar con el punto estándar
            txt_respuesta.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox_verPasswordActionPerformed

    /**
     * Disparador del botón de actualizar.
     */
    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:

        this.actualizar();
    }//GEN-LAST:event_jButton_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JCheckBox jCheckBox_verPassword;
    private javax.swing.JComboBox<String> jComboBox_pregunta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPasswordField txt_respuesta;
    // End of variables declaration//GEN-END:variables

    /**
     * Proceso de negocio para la actualización de la pregunta de seguridad. 
     * 1. Verifica que la respuesta no sea una cadena vacía. 
     * 2. Recupera la selección del ComboBox y el texto del JPasswordField. 
     * 3. Invoca al método actualizarPregunta del Controlador de Usuarios.
     */
    private void actualizar() {

        Usuario usuario = new Usuario();
        Ctrl_Usuario controlUsuario = new Ctrl_Usuario();

        if (txt_respuesta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea guardar los cambios?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {

                usuario.setPregunta((String) jComboBox_pregunta.getSelectedItem());
                usuario.setRespuestapregunta(txt_respuesta.getText().trim());

                if (controlUsuario.actualizarPregunta(usuario, idUsuario)) {
                    JOptionPane.showMessageDialog(this, "Datos Actualizados con Éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                    this.limpiar();           // Limpia campos y resetea ID

                } else {
                    JOptionPane.showMessageDialog(this, "Error al procesar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        }

    }

    private void limpiar() {
        txt_respuesta.setText("");
    }

}
