package Vista;

import Controlador.Ctrl_Categoria;
import Modelo.categoria;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 * Ventana interna para el registro de nuevas categorías de productos. Permite
 * al administrador definir las clasificaciones que se utilizarán posteriormente
 * en el inventario del SCTA.
 *
 * * @author lsuar
 */
public class InterCategoria extends javax.swing.JInternalFrame {

    /**
     * Constructor de la interfaz InterCategoria. Establece las dimensiones
     * básicas y el título de la ventana.
     */
    public InterCategoria() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nueva categoria:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_descripcion.setText(" ");
        txt_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_descripcionKeyPressed(evt);
            }
        });
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gestiona el evento de clic en el botón Guardar. Realiza las siguientes
     * validaciones antes de la persistencia: 1. Que el campo de descripción no
     * esté vacío. 2. Que la categoría no exista previamente en la base de datos
     * (evita duplicados). 3. Confirma el éxito o error de la operación mediante
     * diálogos emergentes.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.guardarCategoria();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_descripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.guardarCategoria();
        }

    }//GEN-LAST:event_txt_descripcionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables
private void guardarCategoria() {

        categoria categoria = new categoria();
        Ctrl_Categoria ctrlcategoria = new Ctrl_Categoria();
        categoria.setDescripcion(txt_descripcion.getText().trim());

        if (txt_descripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo no debe estar vacio.");
        } else {

            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Desea guardar esta nueva categoría?", "Confirmar Registro", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                if (!ctrlcategoria.existeCategoria(txt_descripcion.getText().trim())) {
                    if (ctrlcategoria.guardar(categoria)) {
                        JOptionPane.showMessageDialog(null, "Registro guardado.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "La categoria ya esta registrada en la base de datos.");
                }
            }

        }

        txt_descripcion.setText("");
    }

}
