package Vista;

import Conexion.Conexión;
import Controlador.Ctrl_Producto;
import Modelo.Producto;
import java.sql.*;
import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 * Formulario para el registro de nuevos productos.
 */
public class InterProducto extends javax.swing.JInternalFrame {

    // Variables globales para almacenar los IDs correspondientes a las selecciones de los ComboBox
    int obtenerIdCategoriaCombo = 0;
    int obtenerIdProveedorCombo = 0;

    public InterProducto() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Producto");
        this.cargarCategorias();
        this.cargarProveedores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_descripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_precio = new javax.swing.JTextField();
        jComboBox_IVA = new javax.swing.JComboBox<>();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jComboBox_proveedor = new javax.swing.JComboBox<>();
        jButton_guardar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nuevo Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Precio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, -1));

        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 260, -1));

        jTextField_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_descripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_descripcionKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Categoria:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Proveedor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripción:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("IVA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 50, -1));

        jTextField_precio.setText(" ");
        jTextField_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_precioActionPerformed(evt);
            }
        });
        jTextField_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_precioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_precioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, -1));

        jComboBox_IVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione IVA:", "No Graba IVA", "16% IVA" }));
        jComboBox_IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IVAActionPerformed(evt);
            }
        });
        jComboBox_IVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_IVAKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox_IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, -1));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoría:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaActionPerformed(evt);
            }
        });
        jComboBox_categoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_categoriaKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 180, -1));

        jComboBox_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Proveedor:", "Item 2", "Item 3", "Item 4" }));
        jComboBox_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_proveedorKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 180, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Lógica principal para validar y salvar el producto en la base de datos.
     */
    private void guardarProducto() {
        // 1. Mostrar ventana de confirmación antes de cualquier proceso
        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas guardar este nuevo producto?",
                "Confirmar Registro",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        // 2. Si el usuario selecciona "SÍ" (YES_OPTION), procedemos con la lógica
        if (respuesta == JOptionPane.YES_OPTION) {

            Producto producto = new Producto();
            Ctrl_Producto controlProducto = new Ctrl_Producto();

            String iva = jComboBox_IVA.getSelectedItem().toString().trim();
            String categoria = jComboBox_categoria.getSelectedItem().toString().trim();
            String proveedor = jComboBox_proveedor.getSelectedItem().toString().trim();

            // VALIDACIÓN DE CAMPOS VACÍOS
            if (jTextField_nombre.getText().equals("") || jTextField_descripcion.getText().equals("") || jTextField_precio.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error.", JOptionPane.ERROR_MESSAGE);
            } else {
                // VALIDACIÓN DE DUPLICADOS
                if (!controlProducto.existeProducto(jTextField_nombre.getText().trim())) {

                    // VALIDACIÓN DE SELECCIÓN EN COMBOS
                    if (iva.equalsIgnoreCase("Seleccione IVA:")
                            || categoria.equalsIgnoreCase("Seleccione Categoría:")
                            || proveedor.equalsIgnoreCase("Seleccione Proveedor:")) {

                        JOptionPane.showMessageDialog(this, "Asegúrese de seleccionar IVA, Categoría y Proveedor.");
                    } else {
                        try {
                            // PREPARACIÓN DEL OBJETO
                            producto.setNombre(jTextField_nombre.getText().trim());
                            producto.setDescripcion(jTextField_descripcion.getText().trim());

                            String precioTXT = jTextField_precio.getText().trim().replace(",", ".");
                            producto.setPrecio_unitario(Double.parseDouble(precioTXT));

                            if (iva.equalsIgnoreCase("No Graba IVA")) {
                                producto.setIVA(0);
                            } else if (iva.equalsIgnoreCase("16% IVA")) {
                                producto.setIVA(16);
                            }

                            this.idCategoria();
                            producto.setIdCategoria(obtenerIdCategoriaCombo);
                            this.idProveedor();
                            producto.setIdProveedor(obtenerIdProveedorCombo);

                            // EJECUCIÓN DE LA GUARDA
                            if (controlProducto.guardar(producto)) {
                                JOptionPane.showMessageDialog(this, "Producto Guardado Exitosamente.");
                                this.limpiar();
                                this.cargarCategorias();
                                this.cargarProveedores();
                            } else {
                                JOptionPane.showMessageDialog(this, "Error interno al guardar en la base de datos.");
                            }
                        } catch (HeadlessException | NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "Error de formato en precio: " + e);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El producto ya existe en el sistema.");
                }
            }
        } else {
            // Opcional: Mensaje o acción si el usuario cancela
            System.out.println("Inserción cancelada por el usuario.");
        }
    }

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        this.guardarProducto();
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jTextField_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_descripcion.requestFocus();
        }

    }//GEN-LAST:event_jTextField_nombreKeyPressed

    private void jTextField_descripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_descripcionKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_precio.requestFocus();
        }

    }//GEN-LAST:event_jTextField_descripcionKeyPressed

    private void jTextField_precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_precioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jComboBox_categoria.requestFocus();
            jComboBox_categoria.setPopupVisible(true);
        }

    }//GEN-LAST:event_jTextField_precioKeyPressed

    private void jComboBox_categoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_categoriaKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jComboBox_proveedor.requestFocus();
            jComboBox_proveedor.setPopupVisible(true);
        }

    }//GEN-LAST:event_jComboBox_categoriaKeyPressed

    private void jComboBox_proveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_proveedorKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jComboBox_IVA.requestFocus();
            jComboBox_IVA.setPopupVisible(true);
        }

    }//GEN-LAST:event_jComboBox_proveedorKeyPressed

    private void jComboBox_IVAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_IVAKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.guardarProducto();
        }

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextField_nombre.requestFocus();
        }

    }//GEN-LAST:event_jComboBox_IVAKeyPressed

    private void jTextField_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_precioKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        // Solo permite números y el punto decimal
        if (((caracter < '0') || (caracter > '9')) && (caracter != java.awt.event.KeyEvent.VK_BACK_SPACE) && (caracter != '.') && (caracter != ',')) {
            evt.consume(); // Ignora la tecla
        }

    }//GEN-LAST:event_jTextField_precioKeyTyped

    private void jComboBox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriaActionPerformed

    private void jTextField_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_precioActionPerformed

    private void jComboBox_IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_IVAActionPerformed

    /**
     * NAVEGACIÓN CON TECLA ENTER Estos métodos permiten que el usuario pase de
     * un campo a otro usando Enter
     */
    private void jTextField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyTyped
        // TODO add your handling code here:

        // 1. Obtenemos el carácter presionado
        char car = evt.getKeyChar();

        // 2. Validamos si NO es letra, NO es dígito, NO es espacio, NO es punto y NO es coma
        if (!Character.isLetter(car) && !Character.isDigit(car) && car != ' ' && car != '.' && car != ',') {

            // 3. Si no cumple con ninguna de las anteriores, se "consume" el evento
            evt.consume();
        }

    }//GEN-LAST:event_jTextField_nombreKeyTyped

    private void jTextField_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_descripcionKeyTyped
        // TODO add your handling code here:

        // 1. Obtenemos el carácter presionado
        char car = evt.getKeyChar();

        // 2. Validamos si NO es letra, NO es dígito, NO es espacio, NO es punto y NO es coma
        if (!Character.isLetter(car) && !Character.isDigit(car) && car != ' ' && car != '.' && car != ',') {

            // 3. Si no cumple con ninguna de las anteriores, se "consume" el evento
            evt.consume();
        }

    }//GEN-LAST:event_jTextField_descripcionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JComboBox<String> jComboBox_IVA;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JComboBox<String> jComboBox_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField jTextField_descripcion;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_precio;
    // End of variables declaration//GEN-END:variables

    /**
     * LLENADO DE COMBOS DESDE BD
     */
    private void cargarCategorias() {
        Connection cn = Conexión.conectar();
        String sql = "select * from categoria";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categoria.removeAllItems();
            jComboBox_categoria.addItem("Seleccione Categoria:");

            while (rs.next()) {
                jComboBox_categoria.addItem(rs.getString("descripcion"));
            }

            cn.close();

        } catch (SQLException e) {
        }

    }

    /**
     * LLENADO DE COMBOS DESDE BD
     */
    private void cargarProveedores() {
        Connection cn = Conexión.conectar();
        String sql = "select * from proveedor";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_proveedor.removeAllItems();
            jComboBox_proveedor.addItem("Seleccione Proveedor:");

            while (rs.next()) {
                jComboBox_proveedor.addItem(rs.getString("nombre"));
            }

            cn.close();

        } catch (SQLException e) {
        }

    }

    /**
     * OBTENCIÓN DE ID POR NOMBRE Convierte el texto seleccionado en el Combo al
     * ID (int) de la BD
     */
    private int idCategoria() {
        String sql = "select * from categoria where descripcion = '" + this.jComboBox_categoria.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexión.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdCategoriaCombo = rs.getInt("id_categoria");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al obtener idCategoria.");
        }

        return obtenerIdCategoriaCombo;
    }

    private int idProveedor() {
        String sql = "select * from proveedor where nombre = '" + this.jComboBox_proveedor.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexión.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdProveedorCombo = rs.getInt("id_proveedor");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al obtener idProveedor.");
        }

        return obtenerIdProveedorCombo;
    }

    //Metodo para limpiar campos
    private void limpiar() {
        jTextField_nombre.setText("");
        jTextField_descripcion.setText("");
        jTextField_precio.setText("");
    }

}
