package Vista;

// Importaciones de librerías para manejo de BD, eventos y componentes Swing
import Conexion.Conexión;
import Controlador.Ctrl_Producto;
import Modelo.Producto;
import java.awt.Color;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * Clase para la interfaz interna de configuración de productos. Permite listar,
 * filtrar, actualizar y eliminar productos.
 */
public class InterConfiguracionProductos extends javax.swing.JInternalFrame {

    // Variables de control de estado
    private int idProducto; // Almacena el ID del producto seleccionado en la tabla
    private int obtenerIdCategoriaCombo = 0;
    private int obtenerIdProveedorCombo = 0;
    private DefaultTableModel model; // Modelo para manipular los datos de la JTable
    private TableRowSorter<DefaultTableModel> sorter; // Permite realizar filtros de búsqueda

    public InterConfiguracionProductos() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Configuración de Productos.");

        // Inicialización de componentes personalizados
        this.configurarModeloTabla();
        this.cargarCategorias();
        this.cargarProveedores();

        // Configuración estética del fondo y la tabla
        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);

        // Estilo moderno para la tabla de productos
        jTable_productos.setSelectionBackground(new Color(51, 153, 255));
        jTable_productos.setSelectionForeground(Color.WHITE);
        jTable_productos.setRowHeight(30);
        jTable_productos.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));

        // EVENTO DE SELECCIÓN: Al hacer clic en una fila, recupera el ID y rellena los campos
        jTable_productos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int fila_visual = jTable_productos.getSelectedRow();
                if (fila_visual != -1) {
                    // Convertimos el índice visual al índice del modelo (por si la tabla está filtrada/ordenada)
                    int fila_modelo = jTable_productos.convertRowIndexToModel(fila_visual);
                    String idStr = jTable_productos.getModel().getValueAt(fila_modelo, 0).toString();
                    idProducto = Integer.parseInt(idStr);
                    // Llama al método para traer toda la info de la BD a los campos de texto
                    EnviarDatosProductoSeleccionado(idProducto);
                }
            }
        });
    }

    private void configurarModeloTabla() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Descripción");
        model.addColumn("Categoria");
        model.addColumn("Proveedor");
        model.addColumn("Puntos");

        jTable_productos.setModel(model);
        sorter = new TableRowSorter<>(model);
        jTable_productos.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_refrescar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_proveedor = new javax.swing.JComboBox<>();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_puntos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_categorias = new javax.swing.JComboBox<>();
        txt_buscar = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(340, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 320));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(46, 204, 113));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jButton_eliminar.setBackground(new java.awt.Color(231, 76, 60));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        jButton_refrescar.setBackground(new java.awt.Color(46, 204, 113));
        jButton_refrescar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_refrescar.setText("Refrescar");
        jButton_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 130, 320));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descripción:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 20));

        txt_descripcion.setText(" ");
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        txt_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_descripcionKeyTyped(evt);
            }
        });
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        txt_nombre.setText(" ");
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel3.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Categoria:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Puntos que otorga:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 140, 20));

        jComboBox_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoria:", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 200, -1));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Proovedor:", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Proveedor:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 20));

        txt_puntos.setText(" ");
        txt_puntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puntosActionPerformed(evt);
            }
        });
        txt_puntos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_puntosKeyTyped(evt);
            }
        });
        jPanel3.add(txt_puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 100, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 870, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jComboBox_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Item 2", "Item 3", "Item 4" }));
        jComboBox_categorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_categoriasItemStateChanged(evt);
            }
        });
        jComboBox_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, -1));

        txt_buscar.setText(" ");
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 10, 310, -1));

        jLabel_wallpaper.setText(" ");
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Lógica del botón ACTUALIZAR: Valida campos y envía el objeto Producto al
     * controlador.
     */
    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:

        if (idProducto == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto de la tabla primero.");
            return;
        }

        Producto producto = new Producto();
        Ctrl_Producto controlProducto = new Ctrl_Producto();
        String categoria = jComboBox_categoria.getSelectedItem().toString().trim();
        String proveedor = jComboBox_proveedor.getSelectedItem().toString().trim();

        // Validación de campos vacíos
        if (txt_nombre.getText().isEmpty() || txt_descripcion.getText().isEmpty() || txt_puntos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Validación de ComboBoxes
            if (categoria.equalsIgnoreCase("Seleccione Categoría:")) {
                JOptionPane.showMessageDialog(this, "Seleccione una categoria.");
            } else {
                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea actualizar?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    try {
                        producto.setNombre(txt_nombre.getText().trim());
                        producto.setDescripcion(txt_descripcion.getText().trim());

                        // Obtenemos los IDs numéricos de las llaves foráneas antes de guardar
                        producto.setIdCategoria(this.idCategoria());
                        producto.setIdProveedor(this.idProveedor());
                        producto.setPuntos_otorgados(Integer.parseInt(txt_puntos.getText().trim()));

                        if (controlProducto.actualizarConfiguracion(producto, idProducto)) {
                            JOptionPane.showMessageDialog(this, "Producto Actualizado.");
                            this.organizarPorCategorias(); // Refresca la tabla
                            this.limpiar(); // Limpia el formulario
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error: " + e);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * Lógica del botón ELIMINAR: Borra el registro seleccionado tras confirmación.
     */
    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:

        Ctrl_Producto controlProducto = new Ctrl_Producto();

        if (idProducto == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla.");
        } else {
            // Añadiendo el cuadro de confirmación
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este producto?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                if (controlProducto.EliminarConfiguracion(idProducto)) {
                    JOptionPane.showMessageDialog(null, "¡Producto Eliminado correctamente!");

                    this.organizarPorCategorias();
                    this.cargarCategorias();
                    this.cargarProveedores();
                    this.limpiar();

                    idProducto = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el producto.");
                }
            }
        }

    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarActionPerformed
        // TODO add your handling code here:

        this.organizarPorCategorias();

    }//GEN-LAST:event_jButton_refrescarActionPerformed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_puntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puntosActionPerformed

    private void txt_puntosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_puntosKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        // Solo permite números 
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume(); // Ignora la tecla
        }

    }//GEN-LAST:event_txt_puntosKeyTyped

    private void jComboBox_categoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_categoriasItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            txt_buscar.setText("");
            if (sorter != null) {
                sorter.setRowFilter(null);
            }
            organizarPorCategorias();
        }

    }//GEN-LAST:event_jComboBox_categoriasItemStateChanged

    private void jComboBox_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriasActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
// 1. Obtenemos el carácter presionado
        char car = evt.getKeyChar();

// 2. Validamos si NO es letra, dígito, espacio, punto o coma
        if (!Character.isLetter(car) && !Character.isDigit(car) && car != ' ' && car != '.' && car != ',') {

            // 3. Si no cumple con ninguno de los anteriores, se consume
            evt.consume();
        }

    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionKeyTyped
        // TODO add your handling code here:

        // 1. Obtenemos el carácter presionado
        char car = evt.getKeyChar();

// 2. Validamos si NO es letra, dígito, espacio, punto o coma
        if (!Character.isLetter(car) && !Character.isDigit(car) && car != ' ' && car != '.' && car != ',') {

            // 3. Si no cumple con ninguno de los anteriores, se consume
            evt.consume();
        }

    }//GEN-LAST:event_txt_descripcionKeyTyped

    /**
     * BUSCADOR EN TIEMPO REAL: Filtra la tabla mientras el usuario escribe en 'txt_buscar'.
     */
    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        // TODO add your handling code here:

        String texto = txt_buscar.getText().trim();

        if (texto.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            // Filtra sin importar mayúsculas/minúsculas (?i)
            // El índice 1 corresponde a la columna "Nombre"
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
        }


    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        // TODO add your handling code here:
        
                // 1. Obtenemos el carácter presionado
        char car = evt.getKeyChar();

        // 2. Validamos si NO es letra, NO es dígito, NO es espacio, NO es punto y NO es coma
        if (!Character.isLetter(car) && !Character.isDigit(car) && car != ' ' && car != '.' && car != ',') {

            // 3. Si no cumple con ninguna de las anteriores, se "consume" el evento
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_buscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_refrescar;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JComboBox<String> jComboBox_categorias;
    private javax.swing.JComboBox<String> jComboBox_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_puntos;
    // End of variables declaration//GEN-END:variables

    /**
     * CARGA DE DATOS: Obtiene las categorías de la BD para llenar los ComboBox.
     */
    private void cargarCategorias() {
        Connection cn = Conexión.conectar();
        String sql = "select * from categoria";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categoria.removeAllItems();
            jComboBox_categoria.addItem("Seleccione Categoria:");
            jComboBox_categorias.removeAllItems();
            jComboBox_categorias.addItem("Todos");

            while (rs.next()) {
                jComboBox_categoria.addItem(rs.getString("descripcion"));
                jComboBox_categorias.addItem(rs.getString("descripcion"));
            }

            cn.close();

        } catch (SQLException e) {
        }

    }

        /**
     * CARGA DE DATOS: Obtiene los proveedores de la BD para llenar los ComboBox.
     */
    private void cargarProveedores() {
        Connection cn = Conexión.conectar();
        String sql = "select * from proveedor";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_proveedor.removeAllItems();
            jComboBox_proveedor.addItem("Seleccione Proveedor:");

            while (rs.next()) {
                jComboBox_proveedor.addItem(rs.getString("nombre"));
            }

            cn.close();

        } catch (SQLException e) {
        }

    }

    /**
     * RECUPERACIÓN DE DATOS: Al seleccionar una fila, este método busca el detalle completo en la BD.
     */
    private void EnviarDatosProductoSeleccionado(int idProducto) {
        // 1. Añadimos el WHERE para filtrar por el ID que recibe el método
        String sql = "SELECT p.nombre, p.descripcion, c.descripcion AS categoria, "
                + "prov.nombre AS proveedor, p.puntos_otorgados "
                + "FROM producto p "
                + "INNER JOIN categoria c ON p.id_categoria = c.id_categoria "
                + "INNER JOIN proveedor prov ON p.id_proveedor = prov.id_proveedor "
                + "WHERE p.id_producto = ?";

        try {
            Connection con = Conexión.conectar();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, idProducto);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_nombre.setText(rs.getString("nombre"));
                txt_descripcion.setText(rs.getString("descripcion"));
                txt_puntos.setText(rs.getString("puntos_otorgados"));

                jComboBox_categoria.setSelectedItem(rs.getString("categoria"));
                jComboBox_proveedor.setSelectedItem(rs.getString("proveedor"));
            }
            con.close();
        } catch (SQLException e) {
            System.err.println("Error al obtener datos del producto: " + e);
        }
    }

    private int idCategoria() {
        String sql = "select * from categoria where descripcion = '" + this.jComboBox_categoria.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexión.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdCategoriaCombo = rs.getInt("id_categoria");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al obtener idCategoria.");
        }

        return obtenerIdCategoriaCombo;
    }

    private int idProveedor() {
        String sql = "select * from proveedor where nombre = '" + this.jComboBox_proveedor.getSelectedItem() + "'";
        Statement st;

        try {
            Connection cn = Conexión.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdProveedorCombo = rs.getInt("id_proveedor");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al obtener idProveedor.");
        }

        return obtenerIdProveedorCombo;
    }

    //Metodo para limpiar campos
    private void limpiar() {
        txt_nombre.setText("");
        txt_descripcion.setText("");
        txt_puntos.setText("");
        jComboBox_categoria.setSelectedIndex(0);
        jComboBox_proveedor.setSelectedIndex(0);
    }

    /**
     * FILTRADO POR CATEGORÍA: Reconstruye el contenido de la tabla basado en el JComboBox superior.
     */
    private void organizarPorCategorias() {
        String seleccion = jComboBox_categorias.getSelectedItem().toString();
        model.setRowCount(0); // Limpiar sin recrear el modelo

        String sql = "SELECT p.id_producto, p.nombre, p.descripcion, "
                + "c.descripcion AS categoria, prov.nombre AS proveedor, p.puntos_otorgados "
                + "FROM producto p "
                + "INNER JOIN categoria c ON p.id_categoria = c.id_categoria "
                + "INNER JOIN proveedor prov ON p.id_proveedor = prov.id_proveedor "
                + (seleccion.equals("Todos") ? "" : " WHERE c.descripcion = ?");

        try (Connection cn = Conexión.conectar(); PreparedStatement pst = cn.prepareStatement(sql)) {

            if (!seleccion.equals("Todos")) {
                pst.setString(1, seleccion);
            }

            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5), rs.getInt(6)
                    });
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al filtrar: " + e);
        }
    }

}
